### PR TITLE
Implement delete logic for Arts block

### PR DESCRIPTION
**Pull request by SvyatoS1**

### CODE REVIEW

**Comment by SvyatoS1** [comment]
Need to update story/art_gallery cause its 295 files down, for some reason when i try to update to develop it brings error, so for the time being I keep this pr to merge in develop branch to clearly see file changes.

**Comment by SvyatoS1** [comment]
Also i added FailedToDoOpearionErrors, to simplify this lines:
From:
```
if (!isDeleteSuccessful)
        {
            var errorMsg = $"Failed to delete art with id{request.ArtId}";
            _logger.LogError(request, errorMsg);
            return Result.Fail<DeleteArtResponseDto>(errorMsg);
        }
```
To:
```
 if (!isDeleteSuccessful)
        {
            _logger.LogError(request, FailedToDoOperationErrors.FailedToDeleteArtById);
            return Result.Fail<DeleteArtResponseDto>(FailedToDoOperationErrors.FailedToDeleteArtById);
        }
```
Maybe, the better practice would be to add this resourse file in different branch, leave the comment what do you think about it.

**Comment by SvyatoS1** [comment]
And I saw a small detail: For example in GetAllArtsHandlerTests we see a namespace:
`namespace Streetcode.XUnitTest.MediatRTests.Media.Arts.GetAll;`
But in project its a Art folder:
image
If we fix namespace Arts->Art it will conflict with class Art, and renaming of the folder to Arts also not successful cause Visual Studio do not let that happen to prevent conflicts with other files.

**Review by MrVenik — CHANGES_REQUESTED** [review]
- Destination branch for this feature is `story/arg_gellery`
- Don't forget to format some error message (e.g. `CannotFindEntityErrors.CannotFindArtById` -> `string.Format(CannotFindEntityErrors.CannotFindArtById, artId)`)

**Comment by MrVenik** [comment]
> Need to update story/art_gallery cause its 295 files down, for some reason when i try to update to develop it brings error, so for the time being I keep this pr to merge in develop branch to clearly see file changes.

Oh, we can make PR for pulling from `develop` into `story/art_gallery`

**Comment by MrVenik** [comment]
> Also i added FailedToDoOpearionErrors, to simplify this lines: From:
> 
> ```
> if (!isDeleteSuccessful)
>         {
>             var errorMsg = $"Failed to delete art with id{request.ArtId}";
>             _logger.LogError(request, errorMsg);
>             return Result.Fail<DeleteArtResponseDto>(errorMsg);
>         }
> ```
> 
> To:
> 
> ```
>  if (!isDeleteSuccessful)
>         {
>             _logger.LogError(request, FailedToDoOperationErrors.FailedToDeleteArtById);
>             return Result.Fail<DeleteArtResponseDto>(FailedToDoOperationErrors.FailedToDeleteArtById);
>         }
> ```
> 
> Maybe, the better practice would be to add this resourse file in different branch, leave the comment what do you think about it.

In `interesting facts` block I created `Resources.Errors.CannotCreateEntityErrors.resx`, as for me it is more meaningfull to name this resource as `CannotDeleteEntityErrors`, or if stay with variant `FailedToDoOperationErrors` - we should describe all errors there (e.g. failed to create, update, delete etc)

**Comment by MrVenik** [comment]
> And I saw a small detail: For example in GetAllArtsHandlerTests we see a namespace: `namespace Streetcode.XUnitTest.MediatRTests.Media.Arts.GetAll;` But in project its a Art folder: image If we fix namespace Arts->Art it will conflict with class Art, and renaming of the folder to Arts also not successful cause Visual Studio do not let that happen to prevent conflicts with other files.

I know about this problem, but renaming namespaces can lead us to more problems. In my tests I used `using <entity_name>Entity = <entity_path>;`

**Comment by SvyatoS1** [comment]
> * Don't forget to format some error message (e.g. `CannotFindEntityErrors.CannotFindArtById` -> `string.Format(CannotFindEntityErrors.CannotFindArtById, artId)`)

Done

**Review by MrVenik — APPROVED** [review]
Great job!

**Review by Skilskyi — APPROVED** [review]

**Pull request merged**
