### PR TITLE
Test add tests for all handlers of Team MediatoR

### PR DESCRIPTION
**Pull request by HlibBondarev**

### CODE REVIEW

**Review by SvyatoS1 — COMMENTED** [review]
Good job, but I got few suggestions:
 - Try using file-scoped namespaces
 - I'm not sure, that changes in Program.cs and appsettings is necessary
 - Try not to use region (SA1124)

 Everything else is good, test successfully passed

**Review by MrVenik — CHANGES_REQUESTED** [review]
- Remove changes in Program.cs and appsettings
- Try to use file-scoped namespaces

**Comment by HlibBondarev** [comment]
all issues are resolved:
- used file-scoped namespaces in test files
- cancelled changes in Program.cs and appsettings
- deleted file-scoped namespaces in test files

**Review by MrVenik — APPROVED** [review]
Good job!
As for the future try to separate different handlers into own branches.

**Review by SvyatoS1 — APPROVED** [review]

**Pull request merged**
